---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: cronjob-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpl
    app.kubernetes.io/part-of: dpl
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjob-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
