# permissions for end users to edit payschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: payschedule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpl
    app.kubernetes.io/part-of: dpl
    app.kubernetes.io/managed-by: kustomize
  name: payschedule-editor-role
rules:
- apiGroups:
  - pay.pathao.com
  resources:
  - payschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pay.pathao.com
  resources:
  - payschedules/status
  verbs:
  - get
