---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pay.pathao.com
  resources:
  - payschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pay.pathao.com
  resources:
  - payschedules/finalizers
  verbs:
  - update
- apiGroups:
  - pay.pathao.com
  resources:
  - payschedules/status
  verbs:
  - get
  - patch
  - update
